// Code generated by hand (no controller-gen available). DeepCopy implementations.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *Discovery) DeepCopyInto(out *Discovery) { *out = *in }
func (in *Discovery) DeepCopy() *Discovery {
	if in == nil {
		return nil
	}
	out := new(Discovery)
	in.DeepCopyInto(out)
	return out
}

func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) { *out = *in }
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

func (in *CartSpec) DeepCopyInto(out *CartSpec) {
	*out = *in
	if in.BaseConfigRef != nil {
		out.BaseConfigRef = new(ConfigMapKeyRef)
		*out.BaseConfigRef = *in.BaseConfigRef
	}
}
func (in *CartSpec) DeepCopy() *CartSpec {
	if in == nil {
		return nil
	}
	out := new(CartSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RouteSource) DeepCopyInto(out *RouteSource) { *out = *in }
func (in *RouteSource) DeepCopy() *RouteSource {
	if in == nil {
		return nil
	}
	out := new(RouteSource)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenrestySpec) DeepCopyInto(out *OpenrestySpec) {
	*out = *in
	if in.Sources != nil {
		out.Sources = make([]RouteSource, len(in.Sources))
		copy(out.Sources, in.Sources)
	}
	if in.Values != nil {
		out.Values = make(map[string]string, len(in.Values))
		for k, v := range in.Values {
			out.Values[k] = v
		}
	}
}
func (in *OpenrestySpec) DeepCopy() *OpenrestySpec {
	if in == nil {
		return nil
	}
	out := new(OpenrestySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelRouteSpec) DeepCopyInto(out *ModelRouteSpec) {
	*out = *in
	out.Discovery = in.Discovery
	if in.Cart != nil {
		out.Cart = new(CartSpec)
		in.Cart.DeepCopyInto(out.Cart)
	}
	in.Openresty.DeepCopyInto(&out.Openresty)
}
func (in *ModelRouteSpec) DeepCopy() *ModelRouteSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRouteSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelRouteStatus) DeepCopyInto(out *ModelRouteStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		out.LastSyncTime = in.LastSyncTime.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}
func (in *ModelRouteStatus) DeepCopy() *ModelRouteStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRouteStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelRoute) DeepCopyInto(out *ModelRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *ModelRoute) DeepCopy() *ModelRoute {
	if in == nil {
		return nil
	}
	out := new(ModelRoute)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelRouteList) DeepCopyInto(out *ModelRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ModelRoute, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ModelRouteList) DeepCopy() *ModelRouteList {
	if in == nil {
		return nil
	}
	out := new(ModelRouteList)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
