apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autoconfig.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "autoconfig.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{- include "autoconfig.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "autoconfig.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "autoconfig.serviceAccountName" . }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if not .Values.leaderElection }}
          args:
            - --leader-elect=false
          {{- end }}
          env:
            - name: PS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources: {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
